image:
  name: node:12 #No special docker image.  Standard nodejs image from dockerhub

cache:
  paths:
  - node_modules/

before_script:
  - yarn install
  - node --version

pages:
  stage: deploy
  script:
    # Just to check the files are there.  gitlab needs files in public to move to the host server
    - ls -lFa public
  artifacts:
    paths:
    - public